tap "thoughtbot/formulae"

brew "ccat"
brew "tree"
brew "pstree"
brew "thoughtbot/formulae/rcm"
brew "hub"
brew "rbenv"
brew "awscli"
brew "terraform"
brew "terragrunt"
brew "packer"

cask "google-chrome"
cask "1password"
cask "iterm2"
cask "spectacle"
cask "gpg-suite"
cask "tunnelblick"
cask "sublime-text"
cask "skype"
cask "slack"
cask "telegram"
cask "rubymine"
cask "the-unarchiver"
cask "transmission"
cask "dropbox"
cask "docker"
cask "shuttle"
cask "freemind"
cask "keybase"
cask "fork"
cask "android-file-transfer"
# cask "vlc"
# cask "omnigraffle"
# cask "ngrok"
# cask "java" # Can't be installed from brew cask
